### ISSUE TITLE
volar get an error

### ISSUE THREAD

**Issue by ruinb0w** [yaegassy/coc-volar#342]
I have reinstalled volar and coc multiple times, and if I remove volar, the coc-tsserver is fine to use

```
[coc.nvim]: UnhandledRejection: Error: <syntax> TypeScript Server Error ([object Object])
(0 , language_core_1.buildMappings) is not a function
TypeError: (0 , language_core_1.buildMappings) is not a function
    at /home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@vue/language-core/lib/virtualFile/computedFiles.js:152:6
4
    at Array.map (<anonymous>)
    at /home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@vue/language-core/lib/virtualFile/computedFiles.js:150:2
4
    at /home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/computeds/out/computed.js:13:68
    at Tracker.track (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/computeds/out/tracker.js:43:20)
    at fn (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/computeds/out/computed.js:13:56)
    at /home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@vue/language-core/lib/virtualFile/computedFiles.js:28:79

    at Array.map (<anonymous>)
    at /home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@vue/language-core/lib/virtualFile/computedFiles.js:28:70

    at /home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/computeds/out/computed.js:13:68
    at Tracker.track (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/computeds/out/tracker.js:43:20)
    at fn (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/computeds/out/computed.js:13:56)
    at /home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@vue/language-core/lib/virtualFile/computedFiles.js:31:26

    at /home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/computeds/out/computed.js:13:68
    at Tracker.track (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/computeds/out/tracker.js:43:20)
    at VueVirtualCode.fn [as getEmbeddedCodes] (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/computeds/out/co
mputed.js:13:56)
    at get embeddedCodes [as embeddedCodes] (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@vue/language-core/
lib/virtualFile/vueFile.js:12:21)
    at forEachEmbeddedCode (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@volar/language-core/index.js:227:21
)
    at forEachEmbeddedCode.next (<anonymous>)
    at Object.set (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@volar/language-core/index.js:131:40)
    at /home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@volar/typescript/lib/quickstart/createLanguageServicePlu
gin.js:42:46
    at Object.get (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@volar/language-core/index.js:42:17)
    at updateVirtualScript (/home/ruinb0w/.config/coc/extensions/node_modules/@yaegassy/coc-volar/node_modules/@volar/typescript/lib/node/decorateL
anguageServiceHost.js:92:51)
```

**Comment by yaegassy** [comment]
Hello, it seems there were issues with the dependencies of the upstream packages. These issues have now been resolved.

Please try uninstalling coc-volar once and then reinstalling it to test the latest version.

**Comment by ruinb0w** [comment]
> Hello, it seems there were issues with the dependencies of the upstream packages. These issues have now been resolved.
> 
> Please try uninstalling coc-volar once and then reinstalling it to test the latest version.

It's worked, thank you for you work, it's great!
