### ISSUE TITLE
"CursorHold" error related to Code Lens when launching the extension.

### ISSUE THREAD

**Issue by yaegassy** [yaegassy/coc-volar#6]
There seems to be an error in the background at startup when the Code Lens feature is enabled (`"codeLens.enable": true` in coc-settings.json).

There is nothing wrong with the operation of the extension itself, but it needs to be modified so that the error does not occur.

(As an additional note, this error seems to have occurred since the **early development** of `coc-volar`)

**Log of coc.nvim**:

Repro: `:CocInfo`

```
2021-08-02T08:50:27.543 WARN (pid:18787) [events] - Handler of CursorHold blocked more than 2s: Error
    at Events.on (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:18356:23)
    at CodeLensManager2.listen (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:66679:24)
    at new CodeLensManager2 (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:66671:14)
    at new Handler (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:70517:25)
    at Plugin.init (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:70924:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:71122:11
```

**Capture**:

<img width="1074" alt="coc-volar-issue-startup-backgroud-error" src="https://user-images.githubusercontent.com/188642/127789521-bbb868c3-c7d2-4f9b-9809-f579ba45c217.png">

**Comment by fannheyward** [comment]
I think it's OK to ignore this error.

After coc started, coc will `events.on('CursorHold', ...)` event to force fetch codeLens, but volar maybe not ready at this moment, the handler failed with this warning message. coc will re-fetch/refresh codeLens on CursorHold later, so it's OK to ignore at the launching moment.

coc-volar is great, thank you for your work.

**Comment by yaegassy** [comment]
@fannheyward Thank you for the explanation. I am relieved by fann's explanation.

**Comment by yaegassy** [comment]
This problem is no longer present since volar `v0.28.8`
